
def custom_exception_handler():
    pass